/*
* (c) Copyright, Real-Time Innovations, 2012.  All rights reserved.
* RTI grants Licensee a license to use, modify, compile, and create derivative
* works of the software solely for use with RTI Connext DDS. Licensee may
* redistribute copies of the software provided that all such copies are subject
* to this license. The software is provided "as is", with no warranty of any
* type, including any warranty for fitness for any purpose. RTI is under no
* obligation to maintain or support the software. RTI shall not be liable for
* any incidental or consequential damages arising out of the use or inability
* to use the software.
*/

/* ShapeType_subscriber.c

A subscription example

This file is derived from code automatically generated by the rtiddsgen 
command:

rtiddsgen -language C -example <arch> ShapeType.idl

Example subscription of type ShapeTypeExtended automatically generated by 
'rtiddsgen'. To test it, follow these steps:

(1) Compile this file and the example publication.

(2) Start the subscription on the same domain used for RTI Connext

(3) Start the publication on the same domain used for RTI Connext

(4) [Optional] Specify the list of discovery initial peers and 
multicast receive addresses via an environment variable or a file 
(in the current working directory) called NDDS_DISCOVERY_PEERS. 

You can run any number of publisher and subscriber programs, and can 
add and remove them dynamically from the domain.
*/

#include <stdio.h>
#include <stdlib.h>
#include "ndds/ndds_c.h"
#include "ShapeType.h"
#include "ShapeTypeSupport.h"

#include <signal.h>
#include <pthread.h>

static bool run_flag = true;

#define NUM_SIGS 7


// Local prototypes
void handle_SIGINT(int unused);


//-------------------------------------------------------------------
// handle_SIGINT - sets flag for orderly shutdown on Ctrl-C
//-------------------------------------------------------------------
void handle_SIGINT(int unused)
{
  // On CTRL+C - abort! //
  printf("recieved SIGINT\n");
  run_flag = false;
}

void*  pthreadToProcReaderEvents(void * reader) {
    DDS_DataReader *myReader = NULL;
    myReader = (DDS_DataReader *)reader;
    ShapeTypeExtendedDataReader *shapeTypeExtended_reader = NULL;
    DDS_ReturnCode_t retcode;
    DDS_StatusCondition *status_condition;
    DDS_WaitSet *waitset = NULL;
    struct DDS_Duration_t timeout = { 0, 100000000 }; /* 100ms */
    int count = 0;
    struct DDS_Duration_t delay_period = {1,0}; //sec, nanosec - set to 1/5 sec

    printf("Created Reader Pthread\n");
    if (myReader==NULL){
        printf("ERROR MyReader NULL\n");
    } else {
        printf("MyReader OK\n");
    }

    /// set up and attach desired conditions 
    status_condition = DDS_Entity_get_statuscondition((DDS_Entity *) myReader);
    if (status_condition == NULL) {
        printf("get_statuscondition error\n");
        goto reader_thread_exit;
    }
    printf("Got Status condition\n");

    // Since a single status condition can match many statuses,
    // enable only those we're interested in.
    retcode = DDS_StatusCondition_set_enabled_statuses(
            status_condition,
            DDS_DATA_AVAILABLE_STATUS | DDS_LIVELINESS_CHANGED_STATUS | DDS_SUBSCRIPTION_MATCHED_STATUS);
    if (retcode != DDS_RETCODE_OK) {
        printf("set_enabled_statuses error\n");
        goto reader_thread_exit;
    }

    printf("Enabled Status Conditions\n");

    // Create and attach conditions to the WaitSet
    // * -------------------------------------------
    // * Finally, we create the WaitSet and attach both the Read Conditions
    // * and the Status Condition to it.
    // *
    waitset = DDS_WaitSet_new();
    if (waitset == NULL) {
        printf("create waitset error\n");
        goto reader_thread_exit;
    }

    // Attach Read Conditions 
    retcode = DDS_WaitSet_attach_condition(
            waitset,
            (DDS_Condition *) status_condition);
    if (retcode != DDS_RETCODE_OK) {
        printf("attach_condition error\n");
        goto reader_thread_exit;
    }

    
    shapeTypeExtended_reader = ShapeTypeExtendedDataReader_narrow(myReader);
    if (shapeTypeExtended_reader == NULL) {
        fprintf(stderr, "DataReader narrow error\n");
        goto reader_thread_exit;
    }

    printf("Created Reader Narrow\n");

    // Thread Loop to read evants and data
    
    while(true) {  // CTRL C breaks us out in the main loop and cancels this thread
         //* wait() blocks execution of the thread until one or more attached
         // * Conditions become true, or until a user-specified timeout expires.
         // *
    
        struct DDS_ConditionSeq active_conditions = DDS_SEQUENCE_INITIALIZER;
        int i, j;

        retcode = DDS_WaitSet_wait(waitset, &active_conditions, &timeout);
        if (retcode == DDS_RETCODE_TIMEOUT) {
            printf("wait timed out\n");
            continue;
        } else if (retcode != DDS_RETCODE_OK) {
            printf("wait returned error: %d\n", retcode);
            break;
        }

        printf("got %d active conditions\n",
               DDS_ConditionSeq_get_length(&active_conditions));

        for (i = 0; i < DDS_ConditionSeq_get_length(&active_conditions); ++i) {
            // Compare with Status Conditions 
            if (DDS_ConditionSeq_get(&active_conditions, i)
                == (DDS_Condition *) status_condition) {
                // A status condition triggered--see which ones 
                DDS_StatusMask triggeredmask;
                triggeredmask = DDS_Entity_get_status_changes(
                        (DDS_Entity *) shapeTypeExtended_reader);

                // Subscription matched 
                if (triggeredmask & DDS_DATA_AVAILABLE_STATUS) {
                    // * Current conditions match our conditions to read data, so
                    // * we can read data just like we would do in any other
                    // * example.
                    // *
                    struct ShapeTypeExtendedSeq data_seq = DDS_SEQUENCE_INITIALIZER;
                    struct DDS_SampleInfoSeq info_seq = DDS_SEQUENCE_INITIALIZER;

                    // * Access data using read(), take(), etc.  If you fail to do
                    // * this the condition will remain true, and the WaitSet will
                    // * wake up immediately - causing high CPU usage when it does
                    // * not sleep in the loop 
                    retcode = DDS_RETCODE_OK;
                    while (retcode != DDS_RETCODE_NO_DATA) {
                        retcode = ShapeTypeExtendedDataReader_take(
                                shapeTypeExtended_reader,
                                &data_seq,
                                &info_seq,
                                DDS_LENGTH_UNLIMITED,
                                DDS_ANY_SAMPLE_STATE,
                                DDS_ANY_VIEW_STATE,
                                DDS_ANY_INSTANCE_STATE);

                        for (j = 0; j < ShapeTypeExtendedSeq_get_length(&data_seq); ++j) {
                            if (DDS_SampleInfoSeq_get_reference(&info_seq, j)->valid_data) {
                                printf("Received data\n");
                                ShapeTypeExtendedTypeSupport_print_data(
                                    ShapeTypeExtendedSeq_get_reference(&data_seq, j));
                            }
                        }

                        ShapeTypeExtendedDataReader_return_loan(
                                shapeTypeExtended_reader,
                                &data_seq,
                                &info_seq);
                    }
                }
            }
        }
        
    }
    // Delete all entities 
    reader_thread_exit:

    printf("Reader Thread: Pthread Exiting\n");
    retcode = DDS_WaitSet_delete(waitset);
    if (retcode != DDS_RETCODE_OK) {
        printf("delete waitset error %d\n", retcode);
    }
    fflush(stdout); 
    NDDS_Utility_sleep(&delay_period);
    return(NULL);
}


/* Delete all entities */
static int subscriber_shutdown(
    DDS_DomainParticipant *participant)
{
    DDS_ReturnCode_t retcode;
    int status = 0;

    if (participant != NULL) {
        retcode = DDS_DomainParticipant_delete_contained_entities(participant);
        if (retcode != DDS_RETCODE_OK) {
            fprintf(stderr, "delete_contained_entities error %d\n", retcode);
            status = -1;
        }

        retcode = DDS_DomainParticipantFactory_delete_participant(
            DDS_TheParticipantFactory, participant);
        if (retcode != DDS_RETCODE_OK) {
            fprintf(stderr, "delete_participant error %d\n", retcode);
            status = -1;
        }
    }

    /* RTI Data Distribution Service provides the finalize_instance() method on
    domain participant factory for users who want to release memory used
    by the participant factory. Uncomment the following block of code for
    clean destruction of the singleton. */
    /*
    retcode = DDS_DomainParticipantFactory_finalize_instance();
    if (retcode != DDS_RETCODE_OK) {
        fprintf(stderr, "finalize_instance error %d\n", retcode);
        status = -1;
    }
    */
    printf("Shut Down Particpant\n");
    return status;
}

int subscriber_main(int domainId, int sample_count)
{
    DDS_DomainParticipant *participant = NULL;
    DDS_Subscriber *subscriber = NULL;
    DDS_Topic *topic = NULL;
    DDS_DataReader *reader = NULL;
    DDS_ReturnCode_t retcode;
    const char *type_name = NULL;
    int count = 0;
    struct DDS_Duration_t check_period = {0,200000000}; //sec, nanosec - set to 1/5 sec

    /* To customize participant QoS, use 
    the configuration file USER_QOS_PROFILES.xml */
    participant = DDS_DomainParticipantFactory_create_participant(
        DDS_TheParticipantFactory, domainId, &DDS_PARTICIPANT_QOS_DEFAULT,
        NULL /* listener */, DDS_STATUS_MASK_NONE);
    if (participant == NULL) {
        fprintf(stderr, "create_participant error\n");
        subscriber_shutdown(participant);
        goto subscriber_end;
    }

    /* To customize subscriber QoS, use 
    the configuration file USER_QOS_PROFILES.xml */
    subscriber = DDS_DomainParticipant_create_subscriber(
        participant, &DDS_SUBSCRIBER_QOS_DEFAULT, NULL /* listener */,
        DDS_STATUS_MASK_NONE);
    if (subscriber == NULL) {
        fprintf(stderr, "create_subscriber error\n");
        subscriber_shutdown(participant);
        goto subscriber_end;
    }

    /* Register the type before creating the topic */
    type_name = ShapeTypeExtendedTypeSupport_get_type_name();
    retcode = ShapeTypeExtendedTypeSupport_register_type(participant, type_name);
    if (retcode != DDS_RETCODE_OK) {
        fprintf(stderr, "register_type error %d\n", retcode);
        subscriber_shutdown(participant);
        goto subscriber_end;
    }

    /* To customize topic QoS, use 
    the configuration file USER_QOS_PROFILES.xml */
    topic = DDS_DomainParticipant_create_topic(
        participant, "Square", // "Example ShapeTypeExtended",
        type_name, &DDS_TOPIC_QOS_DEFAULT, NULL /* listener */,
        DDS_STATUS_MASK_NONE);
    if (topic == NULL) {
        fprintf(stderr, "create_topic error\n");
        subscriber_shutdown(participant);
        goto subscriber_end;
    }

    /* To customize data reader QoS, use 
    the configuration file USER_QOS_PROFILES.xml */
    reader = DDS_Subscriber_create_datareader(
        subscriber, DDS_Topic_as_topicdescription(topic),
        &DDS_DATAREADER_QOS_DEFAULT, NULL /* listener */, DDS_STATUS_MASK_ALL);
    if (reader == NULL) {
        fprintf(stderr, "create_datareader error\n");
        subscriber_shutdown(participant);
        goto subscriber_end;
    }

	pthread_t rtid;
    pthread_create(&rtid, NULL, pthreadToProcReaderEvents, (void*) &reader);

	// main loop - reading and writing done in respective threads so nothing to do here
    printf("Main Loop Entered ^C to stop\n");
	while (run_flag == true) {	
        NDDS_Utility_sleep(&check_period);
	}

    //clean up and exit
    pthread_cancel(rtid);
    printf("Cancelled Thread\n");

	subscriber_end: // reached by ^C or an error
    fflush(stdout); 
	return subscriber_shutdown(participant);
}

int main(int argc, char *argv[]) {
    int domain_id = 0;
    int sample_count = 0; /* infinite loop */

    signal(SIGINT, handle_SIGINT);

    if (argc >= 2) {
        domain_id = atoi(argv[1]);
    }
    if (argc >= 3) {
        sample_count = atoi(argv[2]);
    }

    /* Uncomment this to turn on additional logging
    NDDS_Config_Logger_set_verbosity_by_category(
        NDDS_Config_Logger_get_instance(),
        NDDS_CONFIG_LOG_CATEGORY_API, 
        NDDS_CONFIG_LOG_VERBOSITY_STATUS_ALL);
    */

    return subscriber_main(domain_id, sample_count);
}

